### ISSUE TITLE
ORCID authentication not working

### ISSUE THREAD

**Issue by ptgolden** [periodo/periodo-server#99]
To finish up working on patch submission/acceptance, I need to be able to run a local server and authenticate with ORCID. Since upgrading to the latest changes, I'm not able to. It looks like everything goes well until the final step, then there's a missing session variable?

```
127.0.0.1 - - [20/Jun/2018 13:16:21] "GET /register HTTP/1.1" 302 -
127.0.0.1 - - [20/Jun/2018 13:16:21] "GET /registered?code=Hj0huS&state=IOH9R0XOJNKSZPKQ4VVUO5O9K761N61Z HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/home/patrick/Code/projects/periodo-server/periodo/middleware.py", line 13, in __call__
    app_iter = self.app(env, start_response)
  File "/home/patrick/Code/projects/periodo-server/venv/lib/python3.6/site-packages/flask/app.py", line 1985, in wsgi_app
    response = self.handle_exception(e)
  File "/home/patrick/Code/projects/periodo-server/venv/lib/python3.6/site-packages/flask_restful/__init__.py", line 273, in error_router
    return original_handler(e)
  File "/home/patrick/Code/projects/periodo-server/venv/lib/python3.6/site-packages/flask/app.py", line 1540, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/patrick/Code/projects/periodo-server/venv/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/home/patrick/Code/projects/periodo-server/venv/lib/python3.6/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/patrick/Code/projects/periodo-server/venv/lib/python3.6/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/patrick/Code/projects/periodo-server/venv/lib/python3.6/site-packages/flask_restful/__init__.py", line 273, in error_router
    return original_handler(e)
  File "/home/patrick/Code/projects/periodo-server/venv/lib/python3.6/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/patrick/Code/projects/periodo-server/venv/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/home/patrick/Code/projects/periodo-server/venv/lib/python3.6/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/patrick/Code/projects/periodo-server/venv/lib/python3.6/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/patrick/Code/projects/periodo-server/periodo/routes.py", line 155, in registered
    if not request.args['state'] == session.pop('state_token'):
  File "/home/patrick/Code/projects/periodo-server/venv/lib/python3.6/site-packages/werkzeug/datastructures.py", line 255, in pop
    rv = super(UpdateDictMixin, self).pop(key)
KeyError: 'state_token'
```

**Comment by ptgolden** [comment]
Problem shows up after eda32d2

**Comment by rybesh** [comment]
OK, this was also related to SERVER_NAME. Fixed by 86ded3b27152859d2cedcfd8821a4e6f4e4cad36. The dev server must be running on `localhost:5000` (**not** 127.0.0.1:5000) for sessions and ORCID auth to work properly.

**Comment by ptgolden** [comment]
So SERVER_NAME isn't configurable?

(my orcid token is registered for 127.0.0.1:5000, I can try to change it)

**Comment by rybesh** [comment]
SERVER_NAME is configurable, but it has to be a hostname (and optionally a port number), not an IP address (this is a security-related thing that Werkzeug enforces). If SERVER_NAME is an IP address, sessions stop working.

The ORCID app registration for PeriodO had http://127.0.0.1:5000/ as one of the allowed callback endpoints, but this won't work since we started specifying SERVER_NAME (for the reason above), so I changed it to http://localhost:5000/.

If you want to run on a different port, you can, but you need to tell me the port you want so I can update our ORCID app config. I thought it seemed easier to just pick a port and stick with it.
